name: Build for Ubuntu/Debian

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        apt-get update
        apt-get install build-essential pkg-config libclang-19-dev libssl-dev
    - name: Build
      run: cargo deb --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: target/debian/*.deb
